### ISSUE TITLE
how to config my customize game & user 

### ISSUE THREAD

**Issue by elmirarokni** [deeppaz/TwitchtoYoutube#1]
Hi [deeppaz](https://github.com/deeppaz),
please help me how to config this project to use customize game & user 
waitnig for your response
finest regards

**Comment by deeppaz** [comment]
hello,

its still manuel to customize config settings. 
so https://github.com/deeppaz/TwitchtoYoutube/blob/ef0df108216cf63d437cb4c24f53236ef6542f5a/twitch/helpers/getGameId.js#L18 set your fav game from this file. and run
after response game id
https://github.com/deeppaz/TwitchtoYoutube/blob/ef0df108216cf63d437cb4c24f53236ef6542f5a/twitch/getClips.js#L28 write to this line your game id

what do you want to do for user?

**Comment by elmirarokni** [comment]
nothing , but i think this project can bot fetch from specific user or game id .

**Comment by deeppaz** [comment]
yes, you can get specific user clips.
https://github.com/deeppaz/TwitchtoYoutube/blob/main/twitch/helpers/getUserId.js get user id from this file and after you got id https://github.com/deeppaz/TwitchtoYoutube/blob/ef0df108216cf63d437cb4c24f53236ef6542f5a/twitch/getClips.js#L28 in this file on this line. change your `game_id` to `broadcaster_id` thats it. 
more information: check this doc. https://plazide.github.io/node-twitch/interfaces/clip.html#broadcaster_id or you can read official twitch doc

if you want to get more info about for specific user check official twitch doc or https://plazide.github.io/node-twitch/globals.html.
thanks for your insteresting
